CREATE SCHEMA IF NOT EXISTS production;

DROP TABLE IF EXISTS production.dim_zip;

CREATE TABLE IF NOT EXISTS production.dim_zip (
  zip_key  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  zip_code VARCHAR(10) NOT NULL UNIQUE
);